#!/bin/bash

grep -q '^CSF_MASTER|' /etc/csf/csf.blocklists || echo 'CSF_MASTER|43200|400000|https://raw.githubusercontent.com/Aetherinox/csf-firewall/main/blocklists/master.ipset' >> /etc/csf/csf.blocklists; \
grep -q '^BDE|'  /etc/csf/csf.blocklists || echo 'BDE|3600|0|https://api.blocklist.de/getlast.php?time=3600'  >> /etc/csf/csf.blocklists; \
grep -q '^CSF_HIGHRISK|' /etc/csf/csf.blocklists || echo 'CSF_HIGHRISK|43200|0|https://raw.githubusercontent.com/Aetherinox/csf-firewall/main/blocklists/highrisk.ipset' >> /etc/csf/csf.blocklists; \
grep -q '^CSF_PRIVACY_GENERAL|' /etc/csf/csf.blocklists || echo 'CSF_PRIVACY_GENERAL|43200|0|https://blocklist.configserver.dev/privacy_general.ipset' >> /etc/csf/csf.blocklists; \
grep -q '^DSHIELD|' /etc/csf/csf.blocklists || echo 'DSHIELD|86400|0|https://www.dshield.org/block.txt' >> /etc/csf/csf.blocklists; \
sed -i \
  -e 's/^LF_IPSET_MAXELEM = ".*/LF_IPSET_MAXELEM = "400000"/' \
  -e 's/^LF_IPSET = ".*/LF_IPSET = "1"/' \
  -e 's/^DYNDNS = ".*/DYNDNS = "300"/' \
  /etc/csf/csf.conf; \
grep -qxF 'aci.serverfreak.com' /etc/csf/csf.dyndns || echo 'aci.serverfreak.com' >> /etc/csf/csf.dyndns; \
csf -a 10.0.10.223 && csf -a 10.0.7.241 && csf -ra
